// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Amr6qBWd-JRb2nORGNUH5XzgRDLezIA',
    appId: '1:822375769128:web:3aad776ef0bc900492011d',
    messagingSenderId: '822375769128',
    projectId: 'blackjack-21-app',
    authDomain: 'blackjack-21-app.firebaseapp.com',
    storageBucket: 'blackjack-21-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxGzWMxSCkVvGjyBct4m6FBSqlOwxmmjg',
    appId: '1:822375769128:android:adc9972274f9770c92011d',
    messagingSenderId: '822375769128',
    projectId: 'blackjack-21-app',
    storageBucket: 'blackjack-21-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYeNHAO8ctOPpnScWblgtN4cauCCo9y-c',
    appId: '1:822375769128:ios:b170a461cd42f11792011d',
    messagingSenderId: '822375769128',
    projectId: 'blackjack-21-app',
    storageBucket: 'blackjack-21-app.firebasestorage.app',
    iosClientId:
        '822375769128-51k7ugqhfvrba2agqu4cme4jeamoc3iu.apps.googleusercontent.com',
    iosBundleId: 'com.robertgon97.blackjack21',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Amr6qBWd-JRb2nORGNUH5XzgRDLezIA',
    appId: '1:822375769128:web:ade617087fcd262b92011d',
    messagingSenderId: '822375769128',
    projectId: 'blackjack-21-app',
    authDomain: 'blackjack-21-app.firebaseapp.com',
    storageBucket: 'blackjack-21-app.firebasestorage.app',
  );
}
